services:
  app:
    build: .
    container_name: financial_agent_app
    environment:
      - QDRANT_HOST=qdrant_vdb
      - OLLAMA_HOST=http://ollama_llm:11434
      - OLLAMA_MODEL=mistral:7b-instruct-q4_0
      - YOUTUBE_API_KEY=AIzaSyD1hA6jbyKxj6x3m96FM87Dci_MBttsHBY
      - YOUTUBE_CHANNEL_IDS=UCBJycsmduvYEL83R_U4JriQ,UCq9RcdZ2YFxyC6q_Mz0S8xw,UCwLBOxZQ5e3m0h-9B5N6Qxg,UCtUId5WZ07w6bZg7m8z6m2g,UCnh4zO0A7bQKwQ6C2Jr3Hyw,UC5xDht2blPNWdVZ9M2Z9bBg,UCBJycsmduvYEL83R_U4JriQ,UCq9RcdZ2YFxyC6q_Mz0S8xw,UCwLBOxZQ5e3m0h-9B5N6Qxg,UCtUId5WZ07w6bZg7m8z6m2g
      - YOUTUBE_VIDEOS_PER_CHANNEL=5
    volumes:
      - ./src:/app/src
    depends_on:
      - qdrant_vdb
      - ollama_llm
    networks:
      - financial_net
    stdin_open: true
    tty: true

  qdrant_vdb:

    image: qdrant/qdrant:v1.9.2

    container_name: qdrant_vdb
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - financial_net

  ollama_llm:
    image: ollama/ollama:latest
    container_name: ollama_llm
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - financial_net

volumes:
  qdrant_data:
  ollama_data:

networks:
  financial_net:

